# This is a basic workflow to help you get started with Actions

name: Backend Continuous Integration

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-backend:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-backend-lint
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel pytest flake8

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          cd starter/backend
          pipenv install

      - name: Back-end lint
        run: cd starter/backend && pipenv run lint

  test-backend:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-backend-test
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel pytest flake8

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          cd starter/backend
          pipenv install

      - name: Back-end test
        run: cd starter/backend && pipenv run test

  backend-build:
    needs: ['lint-backend','test-backend']
    runs-on: ubuntu-latest
    environment: movie_dev_ops
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        id: build_backend
        shell: bash
        env:
          ECR_REGISTRY: PRE-DEPLOY
          ECR_REPOSITORY: ${{ vars.ECR_BE_REPO_NAME }}
          IMAGE_TAG: latest
        run: |
          cd starter/backend
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" .